### PR TITLE
UserAgent has parentPid for overlay & multi client

### PR DESCRIPTION
**Pull request by MogsFriend**

### CODE REVIEW

**Comment by Styr1x** [comment]
What usecase does having the PID in the browser agent solve? I don't really get it, can you explain?

**Comment by MogsFriend** [comment]
ACT Parse on process selected on log `251 ... |Process ffxiv_dx11 (PID) ...` also alert correct connection for overlays with ws

if you don't think it useful, close this PR

**Comment by Styr1x** [comment]
Thats only relevant for ppl with multiple FFXIV instances, isn't it? Because if its one the PID is easy to find outside of FFXIV.

The user agent string is incorrect, also: Instead of CefSharp version Chromium version should be used and AppleWebKit compatibility changed, also.
The default user agent string reads as follows: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36.

I have an alternative implementation using AgentProduct which results in the following: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Browsingway/1.0.0.1 (ffxiv_pid 12345; render_pid 12345) Safari/537.36

Would that work for you? If you I can add it.

**Comment by MogsFriend** [comment]
it works, thx hearing my small opinion!

**Pull request closed without merging**
